### ISSUE TITLE
Score test suite based on individual properties, instead of entire tests

### ISSUE THREAD

**Issue by orangejulius** [pelias/fuzzy-tests#3]
Currently, if any of the expected properties in the GeoJSON returned from Pelias don't match, the entire test fails. As part of the core idea of fuzzy testing, we want to be a bit more granular and look at each property individually.

**Comment by dianashk** [comment]
This should only require a few new properties in the test suite files. The fuzzy logic needs to happen in the new `fuzzy-tester`.
